class UserError(Exception):
    pass


class ProviderError(Exception):
    pass
